### ISSUE TITLE
Having some trouble with the code here, but NuGet binary works (1.0.3.0)

### ISSUE THREAD

**Issue by GeorgeHahn** [vidstige/Bugsense.WPF#1]
Hi,

I forked the code from this repository in hopes of filling it out a bit - I'd like to add an event for hooking in a 'report' GUI - but I'm having some trouble getting bug reports to send correctly.

I have not been able to isolate any issues. No exceptions are thrown, but the exception does not show up on the Bugsense website. When the Nuget library is used, the bug report shows up without any trouble.

The only thing I've noticed is that when I use the locally compiled version, the Send call seems to take a little longer.

The only difference I see is that the version in this repository is 1.0.2.0 and the version on NuGet is 1.0.3.0.

Thanks!

**Comment by vidstige** [comment]
Thanks for the feedback! It was a huge misstake on my behalf rendering the 1.0.2 version completely useless. I've fixed the code and put up 1.0.3 on NuGet, but I never pushed to github hence this behaviour your observing. I just pushed to github however, so feel free t o try again.

**Comment by GeorgeHahn** [comment]
Thank you sir!
