### ISSUE TITLE
Can you please strong-sign all your .Net binaries delivered via NuGet?

### ISSUE THREAD

**Issue by JanZeman** [vidstige/Bugsense.WPF#3]
Hello, I am getting "Assembly generation failed -- Referenced assembly 'BugSense-...' does not have a strong name" when trying to use the NuGet version. Can you please sign your assemblies? It is a task for 15 minutes work for one developer. Thank you very much in advance. Best regards Jan Zeman

**Comment by vidstige** [comment]
Hi!
Thanks for you feedback. I've strong signed the assemblies. Please try the
1.0.4 version and see if it works for you.

Best regards
/samuel

2013/6/21 JanZeman notifications@github.com

**Comment by JanZeman** [comment]
Thanks a lot, Samuel. It works perfectly :)

**Comment by JanZeman** [comment]
I am sorry, but the assembly I compiled against was still the one I previously built myself (and temporarily signed) and not the one I got via NuGet. My appologies for the confusion. If I download the latest code version I can see there is "Sign assembly" check mark in VS but there is no any .snk file included. One must choose a strong name key file (resp to create a new one, for example Temp.snk). The final check can be this command "sn -vf net40\Bugsense.WPF.dll". Thank you very much in advance, Jan

**Comment by vidstige** [comment]
Sorry, a misstake from my side. My personal private key is not checked in to the git repository, thats probably why you cannot see the snk-file. I tried the `sn -vf` command before pushing this time and it said it was valid. Hopefully it says the same on your side with 1.0.5.

**Comment by JanZeman** [comment]
Yes, this time it seems to be really working. Thank you once again.
